swagger: '2.0'
info:
  version: 0.0.1
  title: OBEJCTDATA SYSTEM - API
  contact:
    email: desenvolvedor@objectdata.com.br
host: development.objectdata.com.br
basePath: /api
tags:
  - name: CEP
    description: Query address by post code.
  - name: Products
    description: 'Registration, consultation and product update.'
  - name: Clients
    description: 'Customer registration, consultation and update.'
  - name: Orders
    description: 'Registration, consultation and order update.'
schemes:
  - http
paths:
  '/cep/{postalCode}':
    get:
      tags:
        - CEP
      summary: Find anddress by postal code
      produces:
        - application/json
      parameters:
        - name: postalCode
          in: path
          description: Postal code to be returned.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Cep'
        '400':
          description: Invalid ID supplied
        '404':
          description: Postal code not found.
definitions:
  Cep:
    type: object
    properties:
      endereco:
        type: string
        example: Rua Carlos da Costa Ramalho Júnior
      cidade:
        type: string
        example: Osasco
      bairro:
        type: string
        example: Presidente Altino
      estado:
        type: string
        example: SP
      cep:
        type: string
        example: '06213110'
